# Homebrew manifest — apps layer for the darwin host (managed via brew).
# Nix (home-manager) handles config; brew handles apps.
#
# Install/update:
#   brew bundle          # install everything in this file
#   brew bundle cleanup  # remove anything not listed here
#   brew upgrade         # update everything
#
# Generated by hand; keep in sync with scripts/setup.sh.

tap "nikitabobko/tap"   # aerospace (cask below)

# ─── Agent CLIs (self-updating; brew owns the binary) ──────────────────────
brew "pi-coding-agent"
brew "herdr"
cask "claude-code"

# ─── Window manager ─────────────────────────────────────────────────────────
cask "aerospace"        # config: home-manager → ~/.config/aerospace/aerospace.toml

# ─── General CLI apps (formerly in packages/stable|unstable|darwin.nix) ─────
brew "gh"
brew "wget"
brew "tree"
brew "direnv"
brew "uv"
brew "bun"
brew "graphviz"
brew "gcc"
brew "curl"
brew "ripgrep"
brew "fd"
brew "gemini-cli"
brew "podman"
brew "nnn"
brew "m-cli"
