require("plugins-setup")
require("core.options")
require("core.keymaps")
require("plugins.catppuccin")
require("plugins.tokyonight-config")
require("core.colorscheme")
-- require("plugins.comment")
require("plugins.nvim-tree")
-- require("plugins.lualine")
require("plugins.telescope")
-- require("plugins.nvim-cmp")
require("plugins.lsp.lspsaga")
-- require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
-- require("plugins.lsp.lsp-signature")
require("plugins.lsp.null-ls")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.gitsigns")
-- require("plugins.solargraph")
-- require("plugins.numb-config")
-- require("plugins.fidget-config")
-- require("plugins.dressing-config")
require("plugins.trouble-config")
require("plugins.legendary-config")
-- require("plugins.leap-config")
-- require("plugins.bufferline-config")
-- require("plugins.leap-config")
require("plugins.indent-blankline-config")
require("plugins.lightbulb-config")
-- require("plugins.notify-config")
-- require("plugins.dart-config")
-- require("plugins.dap-config")
