require("core.options")
require("core.colorscheme")
require("core.keymaps")
-- require("plugins-setup")

require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.bufferline-config")
require("plugins.dressing-config")
require("plugins.feline-config")
-- require("plugins.lsp-config")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.trouble-config")
require("plugins.nvim-tree-config")
require("plugins.fidget-config")
require("plugins.gitsigns-config")
require("plugins.indent-blankline-config")
require("plugins.leap-config")
require("plugins.legendary-config")
require("plugins.lightbulb-config")
require("plugins.notify-config")
require("plugins.numb-config")
require("plugins.dressing-config")
-- require("plugins.dap-config")
