require("core.options")
require("core.keymaps")
require("core.colorscheme")
require("plugins.comment")
require("plugins.cmp-config")
require("plugins.nvim-tree")
require("plugins.telescope")
-- require("plugins.nvim-cmp")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.legendary-config")
require("plugins.indent-blankline-config")
