{ config, inputs, ... }:
let
  system = "aarch64-darwin";
  user = "ianluo";
in {
  flake.homeConfigurations.ianluo = inputs.home-manager.lib.homeManagerConfiguration {
    pkgs = config.repo.mkPkgs system;
    modules = [
      config.flake.modules.homeManager.base
      config.flake.modules.homeManager.stable-packages
        config.flake.modules.homeManager.unstable-packages
      config.flake.modules.homeManager.cli
      config.flake.modules.homeManager.shell
      config.flake.modules.homeManager.tmux
      config.flake.modules.homeManager.editor
      ({ pkgs, ... }: {
        assertions = [
          {
            assertion = user != "";
            message = "Home Manager user must not be empty.";
          }
          {
            assertion = builtins.match "/Users/.*" "/Users/${user}" != null;
            message = "Darwin home directory must stay under /Users.";
          }
        ];

        # allowUnfree comes from config.repo.mkPkgs (modules/repo.nix).

        home.username = user;
        home.homeDirectory = "/Users/${user}";

        # macOS window manager (aerospace) — installed via brew cask; config here.
        xdg.configFile."aerospace/aerospace.toml".text = ''
          # Generated by home-manager (modules/hosts/ianluo.nix)

          [gaps]
          outer.left = 8
          outer.bottom = 8
          outer.top = 8
          outer.right = 8

          [mode.main.binding]
          # Window focus (vim-style)
          alt-h = "focus left"
          alt-j = "focus down"
          alt-k = "focus up"
          alt-l = "focus right"

          # Window movement
          alt-shift-h = "move left"
          alt-shift-j = "move down"
          alt-shift-k = "move up"
          alt-shift-l = "move right"

          # Window management
          alt-q = "close"
          alt-f = "fullscreen"
          alt-g = "layout floating tiling"

          # Layout switching
          alt-comma = "layout accordion horizontal vertical"
          alt-period = "layout tiles horizontal vertical"

          # Resize
          alt-minus = "resize smart -50"
          alt-equal = "resize smart +50"

          # Workspace switching (1-10)
          alt-1 = "workspace 1"
          alt-2 = "workspace 2"
          alt-3 = "workspace 3"
          alt-4 = "workspace 4"
          alt-5 = "workspace 5"
          alt-6 = "workspace 6"
          alt-7 = "workspace 7"
          alt-8 = "workspace 8"
          alt-9 = "workspace 9"
          alt-0 = "workspace 10"

          # Move window to workspace
          alt-shift-1 = "move-node-to-workspace 1"
          alt-shift-2 = "move-node-to-workspace 2"
          alt-shift-3 = "move-node-to-workspace 3"
          alt-shift-4 = "move-node-to-workspace 4"
          alt-shift-5 = "move-node-to-workspace 5"
          alt-shift-6 = "move-node-to-workspace 6"
          alt-shift-7 = "move-node-to-workspace 7"
          alt-shift-8 = "move-node-to-workspace 8"
          alt-shift-9 = "move-node-to-workspace 9"
          alt-shift-0 = "move-node-to-workspace 10"

          # Workspace navigation
          alt-tab = "workspace-back-and-forth"
          alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
        '';

        # Daily nix garbage collection (was nix-darwin's nix.gc)
        launchd.agents.nix-gc = {
          enable = true;
          config = {
            Label = "home-manager.nix-gc";
            ProgramArguments = [ "${pkgs.nix}/bin/nix-collect-garbage" "--delete-older-than" "30d" ];
            StartCalendarInterval = {
              Weekday = 0;
              Hour = 2;
              Minute = 0;
            };
          };
        };

        # AeroSpace service — app installed via brew cask; launchd agent here.
        launchd.agents.aerospace = {
          enable = true;
          config = {
            Label = "home-manager.aerospace";
            Program = "/Applications/AeroSpace.app/Contents/MacOS/AeroSpace";
            KeepAlive = true;
            RunAtLoad = true;
            StandardOutPath = "/tmp/aerospace.log";
            StandardErrorPath = "/tmp/aerospace.err.log";
          };
        };
      })
    ];
  };
}
